### ISSUE TITLE
11/9 작업목록

### ISSUE THREAD

**Issue by pjhjohn** [pjhjohn/djicontroller-server#4]
### 0. Simulation Looper : Related to https://github.com/pjhjohn/djicontroller/issues/5

- [x] Abstract sequential calculations from `control points` to `commands`
- [x] Send `commands` back to client
- [x] Set `terminal conditions` for looping

### 1. Trajectory Optimization
- [x] ~~Keep original Episode Reference control points~~ Copy into `TrajectoryOptimization` model
- [x] Save **intermediate control points**
- [x] ~~Detect **starting point of `simulator output`**~~ => #9
- [x] ~~RE-calculate `simulator output` based on `starting point` & `orientation`~~ => #9
- [x] ~~Calculate **difference between `original control points` and `simulator output`**~~ => #9
- [x] ~~Update `intermediate control points`~~ => #9
- [x] Feedback to client
