### ISSUE TITLE
Trajectory Optimization

### ISSUE THREAD

**Issue by pjhjohn** [pjhjohn/djicontroller-server#6]
- [x] ~~Trim SimulatorLog Data~~ => #9
- [x] ~~Calculate Difference between `State` and `SimulatorLog`~~ => #9
- [x] ~~Define a update policy using `Difference` and `State`~~ => #9
- [x] ~~Update `State` using `policy`~~ => #9
